import * as THREE from './vendor/three.module.js';
const $=id=>document.getElementById(id),data=window.CHAPTERS;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const renderer=new THREE.WebGLRenderer({canvas:$('universe'),antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050912);scene.fog=new THREE.FogExp2(0x050912,.014);
const camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.1,400);camera.position.set(7,4.5,15);
scene.add(new THREE.HemisphereLight(0xddeaff,0x16142d,2.1));const key=new THREE.DirectionalLight(0xadcaff,4);key.position.set(-6,10,9);scene.add(key);const rim=new THREE.PointLight(0xff9b63,100,35);rim.position.set(4,5,-13);scene.add(rim);
const chrome=new THREE.MeshStandardMaterial({color:0xc9d6e9,metalness:.73,roughness:.24});const dark=new THREE.MeshStandardMaterial({color:0x17283e,metalness:.7,roughness:.3});const glow=new THREE.MeshBasicMaterial({color:0xbde6ff});
const guide=new THREE.Group();scene.add(guide);guide.position.set(4.4,0,6);
function mesh(geo,mat,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);return m}
mesh(new THREE.CylinderGeometry(.26,.2,.65,12),chrome,guide,0,1.28,0);mesh(new THREE.SphereGeometry(.26,20,16),chrome,guide,0,1.98,0);mesh(new THREE.BoxGeometry(.33,.1,.12),dark,guide,0,2.02,-.22);mesh(new THREE.BoxGeometry(.25,.025,.13),glow,guide,0,2.02,-.24);mesh(new THREE.SphereGeometry(.2,14,10),dark,guide,0,.9,0);
function limb(x,y,length,radius){const g=new THREE.Group();g.position.set(x,y,0);guide.add(g);mesh(new THREE.SphereGeometry(radius*1.3,12,8),dark,g);mesh(new THREE.CylinderGeometry(radius,radius*.85,length,10),chrome,g,0,-length/2,0);return g}
const leftLeg=limb(-.13,.88,.68,.105),rightLeg=limb(.13,.88,.68,.105),leftArm=limb(-.34,1.54,.65,.075),rightArm=limb(.34,1.54,.65,.075);
mesh(new THREE.BoxGeometry(.19,.12,.34),chrome,leftLeg,0,-.73,-.08);mesh(new THREE.BoxGeometry(.19,.12,.34),chrome,rightLeg,0,-.73,-.08);
const floor=mesh(new THREE.PlaneGeometry(180,260),new THREE.MeshStandardMaterial({color:0x06121f,metalness:.82,roughness:.2}),scene,0,-.04,-75);floor.rotation.x=-Math.PI/2;
// Hexagonal grid carries perspective across the walkable surface.
const lines=[];for(let row=-55;row<12;row++)for(let col=-24;col<25;col++){const x=col*1.55+(row%2)*.775,z=row*1.34;for(let i=0;i<6;i++){const a=i*Math.PI/3,b=(i+1)*Math.PI/3;lines.push(x+Math.cos(a)*.88,.005,z+Math.sin(a)*.88,x+Math.cos(b)*.88,.005,z+Math.sin(b)*.88)}}
const gridGeo=new THREE.BufferGeometry();gridGeo.setAttribute('position',new THREE.Float32BufferAttribute(lines,3));scene.add(new THREE.LineSegments(gridGeo,new THREE.LineBasicMaterial({color:0x386086,transparent:true,opacity:.3})));
const pathMat=new THREE.MeshBasicMaterial({color:0x759dc7,transparent:true,opacity:.28});for(let i=0;i<76;i++){const step=mesh(new THREE.PlaneGeometry(.08,.55),pathMat,scene,2,.015,8-i*1.7);step.rotation.x=-Math.PI/2;const step2=step.clone();step2.position.x=6.6;scene.add(step2)}
const starPositions=[];for(let i=0;i<1800;i++){starPositions.push((Math.random()-.5)*300,Math.random()*120+5,(Math.random()-.5)*300)}const starsGeo=new THREE.BufferGeometry();starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(starPositions,3));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xabc9fb,size:.12,transparent:true,opacity:.85}));scene.add(stars);
// Procedural accretion ring: a black center surrounded by moving hot filaments.
const portalMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{time:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float time;void main(){vec2 p=(vUv-.5)*2.;float r=length(p);float a=atan(p.y,p.x);float swirl=sin(a*43.+r*89.-time*2.)*.018+sin(a*19.-r*70.+time)*.019;float center=.57+swirl;float ring=exp(-pow((r-center)/.045,2.));float outer=exp(-pow((r-.61)/.12,2.));float filaments=pow(.5+.5*sin(a*73.+r*120.-time*3.),3.)*exp(-pow((r-.68)/.09,2.));vec3 c=vec3(1.,.32,.10)*outer*1.5+vec3(1.,.83,.53)*ring*3.+vec3(1.,.55,.24)*filaments;float alpha=max(outer*.75,ring);if(r<.48){c=vec3(.001,.002,.007);alpha=1.;}gl_FragColor=vec4(c,alpha);}`});
const hole=mesh(new THREE.PlaneGeometry(25,25),portalMat,scene,4.4,7,-15);const black=mesh(new THREE.CircleGeometry(6,64),new THREE.MeshBasicMaterial({color:0x010207}),scene,4.4,7,-15.1);
const reflection=mesh(new THREE.PlaneGeometry(22,22),portalMat,scene,4.4,.025,-10);reflection.rotation.x=-Math.PI/2;
const platform=mesh(new THREE.BoxGeometry(6,.22,14),new THREE.MeshStandardMaterial({color:0x101e31,metalness:.8,roughness:.3}),scene,4.4,.02,-10);
const gates=[];const gateGeo=new THREE.TorusGeometry(3.9,.045,8,80);data.forEach((d,i)=>{const group=new THREE.Group();group.position.set(4.4,3.8,-35-i*19);const m=mesh(gateGeo,new THREE.MeshBasicMaterial({color:d.color,transparent:true,opacity:.55}),group);const g2=mesh(new THREE.TorusGeometry(4.3,.013,4,64),new THREE.MeshBasicMaterial({color:d.color,transparent:true,opacity:.3}),group);g2.rotation.z=.3;scene.add(group);const l=new THREE.PointLight(d.color,22,14);l.position.copy(group.position);scene.add(l);gates.push(group)});
let state='intro',chapter=-1,targetZ=guide.position.z,narration=false,phase=0,last=performance.now(),move=0,targetX=4.4,lookX=0,lookY=0;const keys=new Set();
function setHidden(id,yes){$(id).classList.toggle('hidden',yes)}
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();if(!narration)return;const u=new SpeechSynthesisUtterance(text);u.rate=.95;speechSynthesis.speak(u)}
$('sound').onclick=()=>{if(!('speechSynthesis'in window)){$('sound').textContent='Narration unavailable';return}narration=!narration;$('sound').setAttribute('aria-pressed',String(narration));$('sound').querySelector('span').textContent=narration?'Narration on':'Narration off';speak(chapter<0?'Hi, I’m Rishitha. Walk with me through my resume, skills, projects, and ways to connect.':data[chapter].copy)};
function showChapter(i){chapter=i;state='chapter';setHidden('travel',true);setHidden('chapter',false);const d=data[i];$('chapter').classList.toggle('wide',d.kind==='projects'||d.kind==='skills');$('chapterBody').replaceChildren(window.renderChapterItems(d));$('chapterBody').scrollTop=0;$('chapterLabel').textContent=d.label;$('chapterTitle').textContent=d.title;$('chapterCopy').textContent=d.copy;$('chapterTags').replaceChildren(...d.tags.map(t=>{const s=document.createElement('span');s.textContent=t;return s}));$('chapterLink').href=d.link;$('chapterLink').textContent=d.linkLabel;$('next').textContent=i===data.length-1?'Back to the beginning ↻':'Continue journey →';$('previous').disabled=i===0;$('previous').style.opacity=i===0?.3:1;$('location').textContent=d.label;document.querySelectorAll('.chapters button').forEach((b,k)=>b.classList.toggle('active',k===i));speak(d.copy+' '+(d.items||[]).map(item=>item.title+'. '+item.text).join(' '))}
function travel(i,instant=false){setHidden('intro',true);setHidden('sceneCaption',true);setHidden('chapter',true);setHidden('travel',false);setHidden('walkControls',false);if('speechSynthesis'in window)speechSynthesis.cancel();chapter=i;targetZ=-29-i*19;targetX=4.4;state='travel';if(reduced||instant){guide.position.set(4.4,0,targetZ);showChapter(i)}}
function reset(){state='intro';chapter=-1;guide.position.set(4.4,0,6);targetZ=6;targetX=4.4;setHidden('intro',false);setHidden('sceneCaption',false);setHidden('chapter',true);setHidden('travel',true);setHidden('walkControls',true);$('location').textContent='COIMBATORE, INDIA';document.querySelectorAll('.chapters button').forEach(b=>b.classList.remove('active'));if('speechSynthesis'in window)speechSynthesis.cancel()}
$('start').onclick=()=>travel(0);$('next').onclick=()=>chapter===data.length-1?reset():travel(chapter+1);$('previous').onclick=()=>chapter>0&&travel(chapter-1);$('home').onclick=e=>{e.preventDefault();reset()};document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>travel(Number(b.dataset.jump),true));data.forEach((d,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.title=d.label;b.setAttribute('aria-label','Open '+d.label);b.onclick=()=>travel(i,true);$('chapterNav').append(b)});
window.addEventListener('keydown',e=>{if($('details').open||['BUTTON','A'].includes(document.activeElement.tagName)&&!e.key.startsWith('Arrow'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);if(state==='intro'&&(e.key==='w'||e.key==='ArrowUp'))travel(0)}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();move=0});$('walk').addEventListener('pointerdown',e=>{e.currentTarget.setPointerCapture(e.pointerId);move=1});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('walk').addEventListener(type,()=>move=0);
window.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'){lookX=(e.clientX/innerWidth-.5);lookY=(e.clientY/innerHeight-.5)}});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const desired=new THREE.Vector3(),focus=new THREE.Vector3();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;if(document.hidden)return;portalMat.uniforms.time.value=reduced?0:now*.001;let walking=false;if(state==='travel'){let diff=targetZ-guide.position.z;if(Math.abs(diff)<.12){guide.position.z=targetZ;showChapter(chapter)}else{guide.position.z+=Math.sign(diff)*Math.min(Math.abs(diff),dt*6.4);walking=true;guide.rotation.y=diff<0?0:Math.PI}}else if(state==='chapter'){const f=move+(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0);if(f){guide.position.z-=f*dt*3.5;walking=true;guide.rotation.y=f>0?0:Math.PI;if(guide.position.z<targetZ-3.5&&chapter<data.length-1)travel(chapter+1);if(guide.position.z>targetZ+3.5&&chapter>0)travel(chapter-1)}targetX+=(Number(keys.has('d')||keys.has('ArrowRight'))-Number(keys.has('a')||keys.has('ArrowLeft')))*dt*2;targetX=THREE.MathUtils.clamp(targetX,2.7,6);guide.position.x=THREE.MathUtils.lerp(guide.position.x,targetX,.08)}phase+=dt*(walking?9:1);const stride=walking&&!reduced?Math.sin(phase)*.5:0;leftLeg.rotation.x=stride;rightLeg.rotation.x=-stride;leftArm.rotation.x=-stride*.8;rightArm.rotation.x=stride*.8;guide.position.y=walking&&!reduced?Math.abs(Math.sin(phase))* .055:0;if(state==='intro'){desired.set(innerWidth<760?6.5:8,innerWidth<760?5.7:4.1,17);focus.set(innerWidth<760?4:0,4,-8)}else{desired.set(guide.position.x+7.2,4.1,guide.position.z+12);focus.set(guide.position.x-2,2.6,guide.position.z-5)}desired.x+=lookX*.5;desired.y-=lookY*.2;camera.position.lerp(desired,1-Math.exp(-dt*3));camera.lookAt(focus);renderer.render(scene,camera)}requestAnimationFrame(frame);window.sceneReady=true;setHidden('loading',true);
